### ISSUE TITLE
[Task] Review and refactor index.php page

### ISSUE THREAD

**Issue by sashas777** [ReginaBorisova/portfolio#14]
Review the HTML code in the index.php page and find where it can be improved with the usage of PHP variables instead of static text and arrays. Use your experience and best judgment from the previous tasks that have been done. 

### A couple of comments on the refactoring of the code style:

**1. The code snippet**
```
<?=  $ab; ?>
```
Need to be without ";" because you don't have any PHP code after it. A good example of usage would be:
```
<?=$ab?>
```

**2.  Links** need to have a related path. In most cases, you will use an absolute path in the future but it is important to have a relative one in order for the image to be shown on the production server. In the case where you will have your PHP page in a subfolder using URLs without a relative path may bring an issue for the webserver of not finding it.
Example:
```
<a href="about.php"....
```
Should be:
```
<a href="/about.php"...
```
The forward slash "/" means that this file is in the webroot and the webserver will automatically look for it at the https://www..../about.php

The same applies to images. Move the file **WebPagePic.jpg** to the directory and change the URL path  in the <img/> tag.

**3.  Variable names.** A name of a variable should meet the following criteria: 
  - Make sense that by reading it another developer should be able to understand what it is for.
  - have a camelCase format. 
For example
```
 $rm    ='How to reach me';
```
Would be:
```
 $reachMe    ='How to reach me';
```

**4. Migrate inline CSS to a .css file.**
You have lines that have inline CSS:
```
     <div class="portrait"><img src="WebPagePic.jpg" style=" width: 250px;
        height: 250px;   margin: auto;
  border-radius: 50%;
  border: yellow 3px solid;"/></div>
```
The CSS there begins with the "style" property. In good code, it would be inside a .css file. In your project you define a CSS file in the head section (it is correct): https://github.com/ReginaBorisova/portfolio/blob/master/index.php#L17 and you should migrate your inline styles into the .css file.

The final HTML will look like this:
```
<div class="portrait"><img src="WebPagePic.jpg" /></div>
```
This splits different parts of the page into separate files and makes it easy to manage. ]

**Articles:**
 1. https://www.hostinger.com/tutorials/website/how-to-link-a-stylesheet-css-file-to-your-html-file
 2. https://www.hostinger.com/tutorials/website/how-to-create-classes-for-a-responsive-website-on-a-css-file

---

### Tasks

- [ ] Find what else can be improved with variables & arrays
- [ ] Correct the formatting of <?=..?> code
- [ ] Correct links to pages/images
- [ ] Correct variable names
- [ ] Migrate CSS to an external file
