### ISSUE TITLE
[Task] Finalizing The Basic PHP Milestone

### ISSUE THREAD

**Issue by sashas777** [ReginaBorisova/portfolio#15]
Let's get the website to the perfect state:

- [ ] Review the remaining PHP files and analyze what can be changed based on information learned
- [ ]  Modify each file / move images / commit & add it to git
- [ ] Verify that every page works as it used to work and all content is shown
- [ ] Complete the Complex Task
- [ ] Assign back to me to review this ticket before closing it. 

### The Complex Task:

Add at the main page (index.php) after your last name the text: "(Completed x projects)"  where x will be a random number between 1 and 100. 
**Google yourself** on how to create a random number with PHP and **if you won't be able to find** use [this link](https://www.php.net/manual/en/function.rand.php)

**Comment by sashas777** [comment]
@ReginaBorisova 
- [ ] Check the PR comments: https://github.com/ReginaBorisova/portfolio/commit/f62074c03a25b975a2a7386dd50c0953765f2d21
- [ ] Check files for any CSS that is not in the external file
- [ ] Check that there is no static text without a PHP variable
- [ ] Make the year in the footer shown based on PHP instead of text. function date(***)
- [ ] Replace variables from `<?=   $email    ?>` to `<?=$email?>` (Correct code style)
- [ ] Move all images to img directory 
- [ ] Remove unnecessary PHP commented out lines
- [ ] Find where you can use arrays and for each and implement it.

**Comment by sashas777** [comment]
- [ ] https://github.com/ReginaBorisova/portfolio/blob/master/contact.php#L35 extra empty space 
- [ ] https://github.com/ReginaBorisova/portfolio/blob/master/contact.php#L38 use variables
- [ ] https://github.com/ReginaBorisova/portfolio/blob/master/contact.php#L41 same as above. check all files for the same issue, please. 
- [ ] https://github.com/ReginaBorisova/portfolio/blob/master/lesson.php#L11 unnecessary comments.
- [ ] https://github.com/ReginaBorisova/portfolio/blob/master/work.php#L42 - Is there a possibility to use arrays for this block?  If not explain why, please.

**Comment by sashas777** [comment]
- [ ] <?='Monroe, Connecticut'?> shouldn't be there or should be as a variable https://github.com/ReginaBorisova/portfolio/blob/24df8b37a9012b87dbb01050469225e445b0fc89/contact.php#L51

- [ ] https://github.com/ReginaBorisova/portfolio/blob/24df8b37a9012b87dbb01050469225e445b0fc89/work.php#L52 use only lowercase characters for array keys `$project['gitHub']`. there is no difference between lower and upper case so it doesn't make sense to use a different case.

**Comment by sashas777** [comment]
@ReginaBorisova 
The point"shouldn't be there or should be as a variable" is not completed in all files. 
Check the codebase and find where it can be applied, and apply, please.

**Comment by sashas777** [comment]
Please check the comment: https://github.com/ReginaBorisova/portfolio/commit/29ebc778c28399f862dd4754716491550884f723
