### ISSUE TITLE
[Book] Chapter 6 Bringing Forms to Life

### ISSUE THREAD

**Issue by sashas777** [ReginaBorisova/portfolio#24]
Pages 119-156
- [x]  How PHP Gathers Information from a Form  
- [x] Processing and validating User Input
- [ ] Sending Email
- [ ] Handling Multi-Choice Form Elements

**Comment by ReginaBorisova** [comment]
#24 Bringing Form to Life
-Read and took notes on pages 119-128 today

Still working on reading the new info.

**Comment by ReginaBorisova** [comment]
#24 Bringing Form to Life
Keep reading the chapter. 
  - Read and took notes on pages 129-136

Must note that new information absorbs not that easy. But planning to finish the task by the end of the week.
