### ISSUE TITLE
[Task] : Automating a Page’s Title from Its Filename

### ISSUE THREAD

**Issue by sashas777** [ReginaBorisova/portfolio#26]
- [x] Create an array of page titles in the file variables.php.
- [x] Include this file on all PHP pages
- [x] Change a title of a Page dynamically based on the array value and URL.  Book page: 91
