### ISSUE TITLE
[Book] Chapter 7 Using PHP to Manage Files

### ISSUE THREAD

**Issue by sashas777** [ReginaBorisova/portfolio#34]
Pages:  157-191

- [ ] Checking That PHP Can Open a File
- [ ] Reading and Writing to Files
- [ ] Opening and Closing Files for Read/Write Operations
- [ ] Appending Content with fopen(
- [ ] Preventing Overwriting an Existing File
- [ ] Inspecting a Folder with scandir()
- [ ] Inspecting the Contents of a Folder with FilesystemIterator
- [ ] Accessing Remote Files
- [ ] Consuming News and Other RSS Feeds
- [ ] Using SimpleXML
- [ ] Creating a Download Link
