### ISSUE TITLE
[Book] CHAPTER 8 Working with Arrays

### ISSUE THREAD

**Issue by sashas777** [ReginaBorisova/portfolio#36]
Pages: 191-234
Read the book, and experiment as you need. The goal is for you to remember what can be done with arrays and come back to this chapter in the future when you will need to do something with an array. 

**This chapter covers**

- [ ] Understanding various approaches to modify the contents of an array
- [ ] Merging arrays
- [ ] Converting an array to a grammatical string
- [ ] Finding all permutations of an array
- [ ] Sorting arrays
- [ ] Automatically generating nested HTML lists from a multidimensional array
- [ ] Extracting data from JSON
- [ ] Assigning array elements to variables
- [ ] Unpacking arrays with the splat operator

**You may skip:**

- PHP Solution 8-9: Extracting Data from JSON
- PHP Solution 8-10: Using a Generator to Process a CSV File
- Unpacking Arguments from an Array with the Splat
Operator
- PHP Solution 8-11: Processing a CSV File with the Splat Operator

**Comment by ReginaBorisova** [comment]
#36 Working with Arrays.
-refreshed knowledge about operations on array :

 Creation:
Numeric array, Associative array,
Access: By index, By key, Adding/Removing:

Add-Remove by index  Remove by key

Refreshed knowledge about  isset($array[index/key]);

Refreshed Sorting topic;

Read about Looping:

Planning to continue learn left over topics.
