### ISSUE TITLE
[Book] Chapter 9 Uploading Files

### ISSUE THREAD

**Issue by sashas777** [ReginaBorisova/portfolio#37]
Pages: 235 - 267

- [ ] Understanding the $_FILES array
- [ ]  Restricting the size and type of uploads
- [ ] Preventing files from being overwritten
- [ ] Handling multiple uploads

**You may skip:**

- PHP Solution 9-2: Creating the Basic File Upload Class
- PHP Solution 9-6: Adapting the Class to Handle Multiple Uploads

**Read and remember:**

- PHP Solution 9-3: Testing the Error Level, File Size, and MIME Type
- PHP Solution 9-4: Allowing Different Types and Sizes to Be Uploaded
