### ISSUE TITLE
[Book] Chapter 11 Pages That Remember: Simple Login and Multipage Forms

### ISSUE THREAD

**Issue by sashas777** [ReginaBorisova/portfolio#44]
Pages: 293- 329

- [ ] Understanding what sessions are and how to create them
- [ ] Creating a file-based login system
- [ ] Checking password strength with a custom-built class
- [ ] Setting a time limit for sessions
- [ ] Using sessions to keep track of information over multiple pages

**You may skip:**

- PHP Solution 11-2: Buffering the Output with ob_start( )
- PHP Solution 11-3: Creating a Password Strength Checker

**Rememeber**

- Setting a Time Limit on Sessions
