### ISSUE TITLE
[Book] Chapters 12 - 13 Database Basics

### ISSUE THREAD

**Issue by sashas777** [ReginaBorisova/portfolio#46]
Pages: 329 -  394

- [ ] PHPMyAdmin (Alexander)
- [ ] PDO vs MySQLi (Alexander)
- [ ] Understanding how a database stores information
- [ ] Choosing a graphical interface to interact with a database
- [ ] Creating user accounts
- [ ] Defining a database table with the appropriate data types
- [ ] Backing up and transferring data to another server
- [ ] Connecting to MySQL and MariaDB with MySQLi and PDO
- [ ] Counting the number of records in a table
- [ ] Using SELECT queries to retrieve data and display it on a web page
- [ ] Keeping data secure with prepared statements and other techniques

**You may skip** 
- Loading the Images Records from an SQL File
- PHP Solution 13-10: Changing Column Options Through User Input
 

**Remember:**

- Using a Graphical Interface
- Linking Tables with Primary and Foreign Keys
- Creating an SQL File for Backup and Data Transfer
- Connecting with the MySQL Improved Extension
- Connecting with PDO
- PHP Solution 13-2: Counting Records in a Result Set (MySQLi)
- PHP Solution 13-3: Displaying the Images Table Using MySQLi
- PHP Solution 13-4: Counting Records in a Result Set (PDO)
- PHP Solution 13-5: Displaying the Images Table Using PDO
- PDO Connection Crib Sheet
- Understanding the Danger of SQL Injection
- Embedding Variables in MySQLi Prepared Statements
- Binding the Results (Optional)
- PHP Solution 13-7: Using a MySQLi Prepared Statement in a Search
- Embedding Variables in PDO Prepared Statements
- PHP Solution 13-8: Using a PDO Prepared Statement in a Search
