### ISSUE TITLE
[Book] Chapter 15: Database Managing Content

### ISSUE THREAD

**Issue by sashas777** [ReginaBorisova/portfolio#47]
Pages: 415-441

- [ ] Inserting new records in a database table
- [ ] Displaying a list of existing records
- [ ] Updating existing records
- [ ] Asking for confirmation before a record is deleted

**You may skip:**

- Based on the method we use you may read PDO or MySQLi
