### ISSUE TITLE
[Book] Chapter 5: Introducing the PHP Include Commands

### ISSUE THREAD

**Issue by sashas777** [ReginaBorisova/portfolio#7]
Regina:
- [ ] Read the book. Pages 81 - 107 
- [ ] https://www.youtube.com/watch?v=ndMGt7XCoMQ
- [ ] Analyze what parts of the page can be split into different files
- [ ] Understand the difference between include, require, and their _once options.
- [ ] Q&A
- [ ] Workshop on how to split files

**Comment by sashas777** [comment]
I will close it once we will complete the Milestone
