### ISSUE TITLE
[Book] Chapter 5: Creating Pages with Changing Content

### ISSUE THREAD

**Issue by sashas777** [ReginaBorisova/portfolio#8]
Regina:

- [ ] Finish the Chapter 5 (Pages 108-117)

Alexander:

- [x] Page 89:  PHP Solution 5-3: Automatically Indicating the Current Page
- [x] Page 91: PHP Solution 5-4: Automating a Page’s Title from Its Filename
- [x] Page 98: PHP Solution 5-6: Automatically Updating a Copyright Notice
- [x] Page 117:   Nesting Include Files (___DIR___)

**Comment by sashas777** [comment]
@ReginaBorisova  close this task if you read the book, please

**Comment by ReginaBorisova** [comment]
Did the task couple months ago
